version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    command: flask --app flaskr init-db && flask --app flaskr init-db
    volumes:
      - .:/CheetahDashboard




#  db:

#  communication_protocol:
